---
- hosts: jenkins-srv
  remote_user: ubuntu
  become: yes
  vars:
    ansible_ssh_private_key_file: ./elama-test.pem

  tasks: 

  - name: Change Jenkins port from 8080 to 80
    iptables:
      table: nat
      chain: PREROUTING
      protocol: tcp
      match: tcp
      destination_port: 80
      jump: REDIRECT
      to_ports: 8080
    become: yes

  - name: Install add-apt-repostory
    apt: 
      name: software-properties-common 
      state: latest

  - name: Add Oracle Java Repository
    apt_repository: 
     repo: 'ppa:webupd8team/java'

  - name: Accept Java 8 license
    debconf: 
      name: 'oracle-java8-installer' 
      question: 'shared/accepted-oracle-license-v1-1' 
      value: 'true' 
      vtype: 'select'

  - name: Add Jenkins key
    apt_key:
      url: https://jenkins-ci.org/redhat/jenkins-ci.org.key
      state: present

  - name: Add Jenkins APT repository
    shell: echo "deb https://pkg.jenkins.io/debian binary/" >> /etc/apt/sources.list
   
  - name: Update source list
    shell: apt update #better to use apt module but it doesn't work perfect in this case
  
  - name: Install Jenkins and Java
    apt:
      name: "{{ item }}"
      state: latest
    with_items:
      - oracle-java8-installer
      - ca-certificates
      - oracle-java8-set-default
      - jenkins
  
  - name: Get admin password from Jenkin
    shell: cat /var/lib/jenkins/secrets/initialAdminPassword
    register: password

  - name: Print init password jenkins
    debug:
      var: password.stdout

####

- hosts: app-srv,jenkins-srv
  remote_user: ubuntu
  become: yes
  vars:
    ansible_ssh_private_key_file: ./elama-test.pem

  tasks:

  - name: Add Docker key
    apt_key: 
      url: 'https://download.docker.com/linux/ubuntu/gpg'
      state: present

  - name: Add Docker APT repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable

  - name: Install list of packages
    apt:
      name: "{{ item }}"
      state: present
      update_cache: yes
    with_items:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - docker-ce
      
      
####

- hosts: jenkins-srv
  remote_user: ubuntu
  become: yes
  vars:
    ansible_ssh_private_key_file: ./elama-test.pem
  
  tasks:

  - name: Add jenkins user to docker group
    user:
      name: jenkins
      groups: docker
      append: yes


####

- hosts: app-srv
  remote_user: ubuntu
  become: yes
  vars:
    ansible_ssh_private_key_file: ./elama-test.pem
  
  tasks:

  - name: Stop Docker service
    service:
      name: docker
      state: stopped

  - name: Start Docker on 2375 port
    shell: "dockerd -H tcp://0.0.0.0 -H unix:///var/run/docker.sock &"